module.exports = [
  "https://status.tuna.wiki/mirrorz/static/opentuna.json",
  "https://mirrors.ustc.edu.cn/static/json/mirrorz.json",
  "https://mirror.sjtu.edu.cn/mirrorz/siyuan.json",
  "https://mirror.sjtu.edu.cn/mirrorz/zhiyuan.json",
  "https://mirrors.hit.edu.cn/static/mirrorz.json",
  "https://mirrors.dgut.edu.cn/static/mirrorz.json",
  "https://mirrors.sustech.edu.cn/mirrorz/mirrorz.json",
  "https://iptv.uestc.edu.cn/mirrors/mirrorz.json",
  "https://mirrorz.org/static/tmp/bjtu.json",
  "https://mirrorz.org/static/tmp/njupt.json",
  "https://mirrorz.org/static/tmp/cqu.json",
  "https://mirrorz.org/static/tmp/xjtu.json",
  "https://mirrorz.org/static/tmp/tongji.json",
]
